chrismattmann/tika-similarity

- cluster-scores.py
Hi, @chrismattmann  I changed cluster-scores.py file, and let the last cluster included in the clusters.
> add the last cluster into clusters

- cluster-d3.html
- cluster-scores.py
- img.html
- similarity.py
- url_download.py
- value-similarity.py
Hi, @chrismattmann I do not change your file, just add new files because I am not sure whether it is right or not...
The D3 file is 
```
cluster-d3.html. 
```
```
img.html 
```
is used to generate dynamic d3. However, I have not added metadata showing in it.
Thanks.
> add metadata into D3 visualization 

- testdata/clusters3.json
> added clusters for NSIDC images

- cluster-d3.html
Hi @chrismattmann I have uploaded the new version of D3.js. Please check it. Thanks.
> resize d3 based on # of nodes

- circle-packing.py
- circlepacking.html
- cluster-scores.py
- similarity.py
Hi @chrismattmann :
The steps of generating that circle packing viz are (on circle-packing branch right now)
```
1. python similarity.py -f [folder of images]
2. python circle-packing.py 
3. open circlepacking,html
```
Hopefully it works well.
> Circle packing viz for test

- cluster-d3.html
- dynamic-circlepacking.html
- dynamic-cluster.html
Hi, @chrismattmann  I am so sorry that I forget to fix the image path on this viz.
> fixed image path

- circle-packing.py
Hi @chrismattmann . Can you test it?
> changed list split

- circle-packing.py
- compositeViz.html
- dynamic-circlepacking.html
Hi, @chrismattmann  Can you try this out?
**Remember: you have already generated _clusters.json_ and _circle.json_ for this viz.**
```
1. Click the red node(the center of the packing circle). Its cluster viz will show on the right.
2. The color of the circle shows how many attributes. The deeper color shows more same node with the same attribute. 
```
I will talk to Kim about this and ask her for some advise.
Thanks.
> Composite viz built

- compositeViz.html
- value-similarity.py
Hi, @chrismattmann This is the one I showed you in the chat. Can you try this out? 
**Remember: you have already generated _clusters.json_ and _circle.json_ for this viz.**
If not, run as below:
```
1. python similarity.py -f [directory of images] (or  python value-similarity.py -f [directory of images])
2. python cluster-scores.py
3. python circle-packing.py
```
Then, you can open the browser
```
1. Mouseover the center of the cluster circle(in light blue color) , Its cluster viz will show on the right.
2. The color of the circle shows how many attributes. The deeper color shows more same node with the same attribute. 
```
Thanks.
> changed value based similarity for viz

- cluster-d3.html
- compositeViz.html
Hi, @chrismattmann Try it. I changed it binding like **" testdata/circle5.json" and " testdata/clusters5.json"**. You can make it changed to your file name. Any suggestions?
> fixed for large dataset

- cluster-d3.html
- compositeViz.html
- dynamic-cluster.html
- generateLevelCluster.py
- levelCluster-d3.html
Hi, @chrismattmann Completely done. BTW, do I need to add Apache license on the header of each files? And I would like to change the generateLevelCluster.py into a command line file and update Readme.md for this repo if needed.
> added level up cluster for big data viz and fixed mouseover problem

- generateLevelCluster.py
- levelCluster-d3.html
Hi, @chrismattmann changed back file names.
Thanks.
> change back file name

- similarity.py
- value-similarity.py
Please see line 116,118 and 129. Other changes due to my editor automatically removing trailing space.
> fix for #34

- README.md
- cluster-scores.py
I thought it would be nice to be able to change threshold value from the command line. So I added an optional parameter `-t` to set the threshold. If the value is not a valid number, default threshold value is used instead. 
I updated the README as well. These changes shouldn't break anything that depends on the script.
> Setting threshold value from command line 

- value-similarity.py
Hi @chrismattmann 
I would like to merge Fix for Issue https://github.com/chrismattmann/tika-similarity/issues/39
Thank you
> fix for issue #39

- similarity.py
- value-similarity.py
@chrismattmann 
Fetches all files within a given directory recursively while ignoring **.hidden_files** & **.hidden_directories**
Thank you!
> Add directory recursion

- README.md
- edit-value-similarity.py
Hi @chrismattmann 
This PR adds the Edit Distance Metric
Clustering & Visualization is in progress.
Thank you,
Harsha
> add edit-distance metric

- .gitignore
- README.md
- cosine_similarity.py
- edit-value-similarity.py
- vector.py
Hi @chrismattmann 
This PR implements cosine distance metric based off @thammegowda Solr Cosine Distance implementation. Also adds @thammegowda to contributors
Thank you,
Harsha
> add cosine distance

- .gitignore
- README.md
- k-means.py
- vector.py
@chrismattmann This PR implements k-means clustering & visualization by choosing an optimal value of **k** in [2, 3, 4] after computing same
> brute force k-means

- .gitignore
- cosine_similarity.py
Simple one liner fix for https://github.com/chrismattmann/tika-similarity/issues/49
> fix for issue 49

- argK_tika_similarity.py
- vector.py
created a Kmean file with tika similarity implemented within it.
> argK_similarity

- edit-cosine-circle-packing.py
- edit-cosine-cluster.py
Professor @chrismattmann  ,
Modified edit-cosine-circle-packing.py and edit-cosine-cluster.py to cluster based on the command line option passed by the user depending on the necessary use case. Please review and let me know if this is fine.
> Added command line options for clustering based on edit or cosine similarity

- features.py
- metalevenshtein.py
- psykey.py
-Added command line options for stylictic feature similarity. Added more usage description for metalevenshtein and bell curve intersection 
-Moved imports to top
> Commandline changes

- Solr-ES-Similarity/.gitignore
- Solr-ES-Similarity/README.md
- Solr-ES-Similarity/es-similarity.py
- Solr-ES-Similarity/generic-solr-schema.xml
- Solr-ES-Similarity/ingest.py
- Solr-ES-Similarity/preprocess_ground.py
- Solr-ES-Similarity/solr-similarity.py
- Solr-ES-Similarity/solr.py
- Solr-ES-Similarity/static/dynamic-cluster-kmeans.html
- Solr-ES-Similarity/static/dynamic-cluster-value.html
- Solr-ES-Similarity/static/dynamic-cluster.html
- Solr-ES-Similarity/vector.py
@chrismattmann Adding solr similarity
Fixes https://github.com/chrismattmann/tika-similarity/issues/64
Thanks!
> add solr similarity

- vector.py
Updated to read attributes and their datatypes form config file for better representation. config file will be of format attribute_name:datatype, ex : location:string. If the attribute is a string it is converted to its hash, int and float are retained, date is converted to epoch.
Example config.txt file :
location:string
reported_date:date
population:int
latitude:double
> updated vector.py to select attributes from config file

- indented_tree.html
CS 599: Team 3 as a part of extra credit for assignment 1
> Adding indented tree visualization using d3

- cluster_barchart.html
Displays a bar chart where each bar represents a cluster with the length corresponding to the number of objects in the cluster. Hover to see cluster name and count.
> Created d3 barchart visualization

- .gitignore
- README.md
- Solr-ES-Similarity/ingest.py
- Solr-ES-Similarity/preprocess_ground.py
- Solr-ES-Similarity/solr.py
- affinity_propagation.py
- argK-means.py
- circle-packing.py
- cluster-scores.py
- cosine_similarity.py
- edit-cosine-circle-packing.py
- edit-cosine-cluster.py
- edit-cosine-correlation-matrix.py
- edit-value-similarity.py
- features.py
- jaccard_similarity.py
- metalevenshtein.py
- requirements.txt
- similarity.py
- sk_kmeans.py
- sunburst.py
- tree_map.py
- value-similarity.py
- vector.py
This is the PR to upgrade tika-simmilarity to Python3. I have also included more detailed instructions on installation to better improve user experience (Installing Java Development Kit and having a requirements.txt file). Chris, please email/slack me if you have any issues, thanks a bunch!
> Upgrade to Python3
